apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: books-manager
rules:
- apiGroups:
  - example.com
  resources:
  - books
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
